"""Replace chunk-section FK with many-to-many join table and drop section end_offset

Revision ID: 419ed0ac8ad2
Revises: 7312cc519589
Create Date: 2026-04-10 18:59:19.878318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419ed0ac8ad2'
down_revision: Union[str, Sequence[str], None] = '7312cc519589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_chunk_section',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['resource_chunk.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['resource_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', 'section_id')
    )
    with op.batch_alter_table('resource_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_chunk_section_id'))
        batch_op.drop_constraint(batch_op.f('fk_resource_chunk_section_id'), type_='foreignkey')
        batch_op.drop_column('section_id')

    with op.batch_alter_table('resource_section', schema=None) as batch_op:
        batch_op.drop_column('end_offset')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_offset', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('resource_chunk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_resource_chunk_section_id'), 'resource_section', ['section_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_resource_chunk_section_id'), ['section_id'], unique=False)

    op.drop_table('resource_chunk_section')
    # ### end Alembic commands ###
