"""add resource sections and source storage

Revision ID: 7312cc519589
Revises: fa2217307327
Create Date: 2026-04-01 21:38:51.217424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7312cc519589'
down_revision: Union[str, Sequence[str], None] = 'fa2217307327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['resource_section.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'position')
    )
    with op.batch_alter_table('resource_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_section_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_section_resource_id'), ['resource_id'], unique=False)

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_bytes', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('source_metadata', sa.JSON(), nullable=True))

    with op.batch_alter_table('resource_chunk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_resource_chunk_section_id'), ['section_id'], unique=False)
        batch_op.create_foreign_key('fk_resource_chunk_section_id', 'resource_section', ['section_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_chunk', schema=None) as batch_op:
        batch_op.drop_constraint('fk_resource_chunk_section_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_resource_chunk_section_id'))
        batch_op.drop_column('section_id')

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.drop_column('source_metadata')
        batch_op.drop_column('source_bytes')
        batch_op.drop_column('source_type')

    with op.batch_alter_table('resource_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_section_resource_id'))
        batch_op.drop_index(batch_op.f('ix_resource_section_parent_id'))

    op.drop_table('resource_section')
    # ### end Alembic commands ###
