"""initial schema

Revision ID: a395173f659e
Revises: 
Create Date: 2026-03-26 14:21:46.958372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a395173f659e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ephemeral', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('additional_args', sa.JSON(), nullable=True),
    sa.Column('user_instructions', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('final_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name')
    )
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_parent_id'), ['parent_id'], unique=False)

    op.create_table('flashcard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('testing_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flashcard_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flashcard_topic_id'), ['topic_id'], unique=False)

    op.create_table('knowledge_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('additional_notes', sa.Text(), server_default='', nullable=False),
    sa.Column('entry_type', sa.Enum('fact', 'exposition', 'overview', name='entrytype'), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('speed_testable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_entry_topic_id'), ['topic_id'], unique=False)

    op.create_table('review_session_topic',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'topic_id'),
    sa.UniqueConstraint('session_id', 'topic_id')
    )
    op.create_table('flashcard_entry',
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['knowledge_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcard.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flashcard_id', 'entry_id'),
    sa.UniqueConstraint('flashcard_id', 'entry_id')
    )
    op.create_table('knowledge_entry_tag',
    sa.Column('knowledge_entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_entry_id'], ['knowledge_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_entry_id', 'tag_id')
    )
    op.create_table('related_knowledge_entries',
    sa.Column('source_entry_id', sa.Integer(), nullable=False),
    sa.Column('target_entry_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.CheckConstraint('source_entry_id != target_entry_id', name='no_self_loop'),
    sa.ForeignKeyConstraint(['source_entry_id'], ['knowledge_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entry_id'], ['knowledge_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_entry_id', 'target_entry_id')
    )
    op.create_table('review_interaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('user_response', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 5', name='score_range'),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcard.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_interaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_interaction_flashcard_id'), ['flashcard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_interaction_session_id'), ['session_id'], unique=False)

    op.create_table('review_session_entry',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['knowledge_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'entry_id'),
    sa.UniqueConstraint('session_id', 'entry_id')
    )
    op.create_table('review_interaction_entry',
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['knowledge_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interaction_id'], ['review_interaction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interaction_id', 'entry_id'),
    sa.UniqueConstraint('interaction_id', 'entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_interaction_entry')
    op.drop_table('review_session_entry')
    with op.batch_alter_table('review_interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_interaction_session_id'))
        batch_op.drop_index(batch_op.f('ix_review_interaction_flashcard_id'))

    op.drop_table('review_interaction')
    op.drop_table('related_knowledge_entries')
    op.drop_table('knowledge_entry_tag')
    op.drop_table('flashcard_entry')
    op.drop_table('review_session_topic')
    with op.batch_alter_table('knowledge_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_entry_topic_id'))

    op.drop_table('knowledge_entry')
    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flashcard_topic_id'))
        batch_op.drop_index(batch_op.f('ix_flashcard_session_id'))

    op.drop_table('flashcard')
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_parent_id'))

    op.drop_table('topic')
    op.drop_table('tag')
    op.drop_table('review_session')
    # ### end Alembic commands ###
